apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-project
  labels:
    app: argocd
spec:
  sourceRepos:
  - "https://github.com/AlphaBril/*"
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
